- WebApp.html
- index.html
Added basic topics for web application architecture in easy to digest tidbits.
> Added a new section "Web Application Fundamentals"

- styles.css
Added transition and styles to the checkboxes <br>
> Styling Checkboxes

- index.html
- script.js
- styles.css
It will take a little time to load as I am not using a paid api .. Free api request using script tag in html is is making the api slow but the feature is working ... You can merge it
> Added new quote on refresh feature

- algorithm.html
- index.html
I've added checklist for Algorithm Design Techniques.
> added ad techniques

- JavaBasic.html
- index.html
- script.js
- styles.css
Added Baisc of Java with Basic Code Snippets
> Added Java Section with Code Examples(Snippets)

- index.html
- python_Basics.html
- styles.css
Python language added
---->Intro to python
---->Variables & Data types [ with examples ]
---->Conditional statements [ with examples ]
---->Functional programming [ with examples ]
---->Sets with examples added
---->Tuple with examples added
---->Dictionary with examples added
---->Loops with examples added
Alignment changed to center on main page topics [c++ basics, python basics etc..] for better look and visibility
>  python with examples added & center aligned main page topics for slight better look

- index.html
- linux.html
> [FEAT] Added Linux notes 

- golang.html
- index.html
> [ADD] Golang basics content

- algorithm.html
Hey @UjjwalSharma01 
I have added all the important algorithms in algorithm.html
Kindly go through it and give me feedback. 
Thanking You!
> Added All important algorithms

- frontendProjects.html
- index.html
Hey @UjjwalSharma01 
Issue No #109 
I have created new folders for front-end Projects. 
I have uploaded one of my frontend projects to it. 
It is a snake game with an interactive frontend UI. 
Please approve and give feedback. 
Thanking You!
> Added Frontend Projects folder

- dark-mode.css
- index.html
- script.js
- styles.css
fixes #15
These PR will fixes #15 which adds responsive navbar , please review and merge the PR and feel free to update here.
> fix: Added responsive navigation bar with hamburger menu icon

- JavaBasic.html
fixes #120 
I add the notes. After review this please marge this branch
> Fix: Adding java exception handing notes

- index.html
- styles.css
I have added a responsive and beautiful Footer in the Home page.
You can check my work form here : https://rko0211.github.io/checklist/
Kindly review my PR and Merge under Apertre24. Thank you.
Fixes issue #125
> Add Responsive and beautiful Footer 

- frontendProjects.html
Hello sir...I have added a new project, Quote generator. Issue #130 
Please review it
> Added new project

- index.html
- styles.css
> css changes

- C++_Basics.html
- C_Programming.html
- JavaBasic.html
- OOP.html
- STL.html
- Vector.html
- WebApp.html
- algorithm.html
- frontendProjects.html
- golang.html
- linux.html
- python_Basics.html
- styles.css
Kindly review my PR and merge it under apertre24.
Fixes issue :  #135
> Add footer in all pages

- dark-mode.css
- dark-mode.js
- styles.css
> changed UI

- frontendProjects.html
- styles.css
> added frontend projs

- contact.css
- contact.html
- dark-mode.js
- styles.css
> Update Contact Page

- index.html
- script.js
- styles.css
> #164 issue added a scroll to top arrow

- index.html
- script.js
now top to scroll arrow button  does not refresh instead scrolls up
> issue #164 fixed the refresh problem of scroll to top arrow button

- app.js
- contact.css
- contact.html
- particles.js
issue #181 
and pls assign me for issue#182 if u like the particle effect , i can add it to every page
> changed contact us form

- app.js
- contact.css
- contact.html
- dark-mode.css
- dark-mode.js
- index.html
- particles.js
- styles.css
> Dark mode issue

- Contribute.html
- index.html
Kindly review my PR.
Resolve issue #175
> Add animation on scrolling

- index.html
- script.js
- styles.css
> fixed menu issue

- styles.css
Kindly review my PR.
Resolve issue #174
> Add Good Font style for various Browsers

- contact.css
> Update font of input box of Contact page
